config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show]
  resources :users, only: [:show, :edit, :update]
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'places#index'
  post 'cart/add' => 'cart#add', :as => 'cart_add'
  post 'cart/minus' => 'cart#minus', :as => 'cart_minus'
  post 'cart/plus' => 'cart#plus', :as => 'cart_plus'
  post 'cart/remove' => 'cart#remove', :as => 'cart_remove'
  post 'cart/clear' => 'cart#clear', :as => 'cart_clear'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        cannot :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :place
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :items

	has_attached_file :image,
  									styles: { medium: '300x300>', thumb: '100x100>' },
  									default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image,
  									content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders, dependent: :destroy

  def admin?
  	self.role == 'admin'  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions

  def access_denied(exception)
    flash[:notice] = exception.message
    redirect_to root_url
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate_user!

	def add
		place = params[:place]
		item = params[:item]
		count = params[:count].to_i

		user_session[place] ||= {}

		user_session[place][item] = count

		flash[:notice] = "Items was added"
		redirect_to place_path(place)
	end

	def minus
		place = params[:place]
		item = params[:item]

		if user_session[place][item] > 1
			user_session[place][item] -= 1
			flash[:notice] = "Count was changed."
		else
			flash[:alert] = "Items in cart must be more than 1. "
		end
		redirect_to place_path(place)
	end

	def plus
		place = params[:place]
		item = params[:item]

		if user_session[place][item] < 10
			user_session[place][item] += 1
			flash[:notice] = "Count was changed."
		else
			flash[:alert] = "Items in cart must be less than 10. "
		end
		redirect_to place_path(place)
	end

	def remove
		place = params[:place]
		item = params[:item]

		user_session[place].delete(item)
		flash[:notice] = "Item was deleted."

		redirect_to place_path(place)		
	end

	def clear
		place = params[:place]
		user_session[place] = {}	

		flash[:alert] = "Cart was cleared."
		redirect_to place_path(place)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def index
		@orders = User.find(current_user).orders
	end

	def show
		@order = Order.find(params[:id])	
	end

	def create
		user = current_user
		place = params[:place]
		total = params[:total]
		order = Order.create(user: user, total: total)		

		user_session[place].each do |item, count|
			order.order_items.create(item_id: item.to_i, count: count)
		end

		user_session[place] = {}
		flash[:notice] = "Order was created."
		redirect_to order
	end

	def destroy
		Order.destroy(params[:id])
		flash[:notice] = "Order was destroyed."
		redirect_to orders_path
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all
	end

	def show
		@place = Place.find(params[:id])	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :true_user, only: [:edit, :update]

	def show
		@user = User.find(current_user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to user_path(@user)
			flash[:notice] = "Information successfully updated"	
		else
			render 'edit'
		end
	end

	private

	def true_user
		redirect_to edit_user_path(current_user) if current_user.id.to_s != params[:id]
	end

	def user_params
		params.require(:user).permit(:name, :phone, :address)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/_cart_item.html.erb
<div class="panel-body">
	<div class="row" id="<%= "cart-item-" + item.id.to_s %>">
		<div class="col-md-5">
			<h4 class="product-name"><strong><%= item.name %></strong></h4>
		</div>
		<div class="col-md-7">
			<div class="col-md-9 text-right">
				<h5>
					<strong>
						<%= link_to cart_minus_path(place: item.place, item: item), method: :post do %>
						<i class="glyphicon glyphicon-minus"></i>
						<% end %>
						<%= item.price %> х <%= count %>
						<%= link_to cart_plus_path(place: item.place, item: item), method: :post do %>
						<i class="glyphicon glyphicon-plus"></i>
						<% end %>
					</strong>
				</h5>
			</div>
			<div class="col-md-3">
				<h5>
					<strong>					
						<%= link_to cart_remove_path(place: item.place, item: item), method: :post do %>
						<i class="glyphicon glyphicon-trash"></i>
						<% end %>
					</strong>
				</h5>
			</div>
		</div>
	</div>
</div>

app/views/carts/_cart.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<div class="panel-title">
			<div class="row">
				<div class="col-xs-12">
					<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart for <%= @place.name %></h5>
				</div>
			</div>
		</div>
	</div>

	<% total = 0 %>
	<% user_session.each do |place, items| %>
	<% next if place != @place.id.to_s %>
	<% items.each do |item, count| %>
	<% item = Item.find(item)%>
	<% total += item.price * count.to_f %>
	<%= render 'cart_items/cart_item', item: item, count: count %>
	<% end %>
	<% end %>	

	<div class="panel-footer">
		<div class="row text-center">
			<div class="col-xs-6">
				<h4 class="text-right">Total <strong><%= total %></strong></h4>
			</div>
			<div class="col-xs-6">
				<%= link_to 'Clear', cart_clear_path(place: @place), method: :post, class: 'btn btn-danger' %>
				<%= link_to 'Checkout', orders_path(place: @place, total: total), method: :post, class: 'btn btn-success' %>
			</div>
		</div>
	</div>

</div>

app/views/items/_item.html.erb
<div class="panel panel-default  panel--styled">
	<div class="panel-body">
		<div class="col-md-12 panelTop">
			<div class="col-md-4">  
				<img class="img-responsive" src="http://placehold.it/350x350" alt=""/>
			</div>
			<div class="col-md-8">  
				<h2><%= item.name %></h2>
				<p><%= item.about %></p>
			</div>
		</div>

		<div class="col-md-12 panelBottom">            
			<div class="col-md-4 text-left">
				<h4>Цена: <span class="itemPrice"> <%= item.price %> сом</span></h4>
			</div>
			<%= link_to 'Add to cart', cart_add_path(place: item.place, item: item, count: 1), method: :post, class: 'btn btn-add-to-cart', id: "item-#{item.id}"%>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Get Food</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<%= link_to "Food Store", root_path, class: 'navbar-brand'%>
				<% if notice %>
				<p class="navbar-text" id="alert"><%= notice %></p>
				<% end %>
				<% if alert %>
				<p class="navbar-text" id="alert"><%= alert %></p>
				<% end %>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to('Profile', user_path(current_user)) %></li>
							<li><%= link_to('Orders', orders_path) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to('Edit', edit_user_path(current_user)) %></li>
							<li><%= link_to('Settings', edit_user_registration_path) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to('Sign in', new_user_session_path) %></li>
					<li><%= link_to('Sign up', new_user_registration_path) %></li>
					<% end %>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	
	<div class="container">		
		<%= yield %>
	</div>
	<script type="text/javascript">
		$("#alert").delay(1500).fadeOut();
	</script>
</body>
</html>

app/views/order_items/_order_item.html.erb
<li class="list-group-item">
    <span class="prefix">
        <%= order_item.count %>
        <%= order_item.item.name %>
    </span>
</li>

app/views/orders/_order.html.erb
<tr>
	<td><%= order.id %></td>
	<td><%= order.order_items.last.item.place.name %></td>
	<td><%= order.total %></td>
	<td>New</td>
	<td class="text-center">
		<%= link_to order_path(order), class: "btn btn-success btn-xs" do %>
		<span class="glyphicon glyphicon-eye-open"></span> Show
		<% end %>
		<%= link_to root_path, class: "btn btn-info btn-xs" do %>
		<span class="glyphicon glyphicon-edit"></span> Edit
		<% end %>
		<%= link_to order_path(order), method: :delete, class: "btn btn-danger btn-xs" do %>
		<span class="glyphicon glyphicon-remove"></span> Delete
		<% end %>
	</td>
</tr>

app/views/orders/index.html.erb
<div class="container">
    <div class="row col-md-6 col-md-offset-2 custyle">
    <table class="table table-striped custab">
    <thead>
        <h3>My orders:</h3>
        <tr>
            <th>ID</th>
            <th>From</th>
            <th>Total</th>
            <th>Status</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
        <%= render @orders %>
    </table>
    </div>
</div>

app/views/orders/show.html.erb
<div class="row shop-tracking-status">

    <div class="col-md-12">
        <div class="well">
            <h4>Ordered items:</h4>
            <ul class="list-group">
                <%= render @order.order_items %>
            </ul>
            <h4>Your order status:</h4>

            <ul class="list-group">
                <li class="list-group-item">
                    <span class="prefix">Date created:</span>
                    <span class="label label-success"><%= @order.created_at.strftime("%d %b. %Y" + " " +  "%H:%M")%></span>
                </li>
                <li class="list-group-item">
                    <span class="prefix">Last update:</span>
                    <span class="label label-success"><%= @order.updated_at.strftime("%d %b. %Y" + " " +  "%H:%M")%></span>
                </li>
                <li class="list-group-item">
                    <span class="prefix">Comment:</span>
                    <span class="label label-success">customer's comment goes here</span>
                </li>
                <li class="list-group-item">You can find out latest status of your order with the following link:</li>
                <li class="list-group-item"><a href="//tracking/link/goes/here">//tracking/link/goes/here</a></li>
            </ul>

            <div class="order-status">

                <div class="order-status-timeline">
                    <!-- class names: c0 c1 c2 c3 and c4 -->
                    <div class="order-status-timeline-completion c3"></div>
                </div>

                <div class="image-order-status image-order-status-new active img-circle">
                    <span class="status">Accepted</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-active active img-circle">
                    <span class="status">In progress</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-intransit active img-circle">
                    <span class="status">Shipped</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-delivered active img-circle">
                    <span class="status">Delivered</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-completed active img-circle">
                    <span class="status">Completed</span>
                    <div class="icon"></div>
                </div>

            </div>
        </div>
    </div>

</div>

app/views/places/_place.html.erb
<div class="panel panel-default  panel--styled">
  <div class="panel-body">
    <div class="col-md-12 panelTop">  
      <div class="col-md-4"> 
        <%= image_tag place.image.url, class: 'img-responsive', size: '350x350' %>
      </div>
      <div class="col-md-8">  
      <h2><%= place.name %></h2>
        <p><%= place.about %></p>
      </div>
    </div>

    <div class="col-md-12 panelBottom">
      <div class="col-md-4 text-center">
        <% if action_name == "show" %>
          <%= link_to places_path, class: "btn btn-lg btn-add-to-cart" do %>
          <i class="glyphicon glyphicon-arrow-left"></i> Назад
          <% end %>
        <% else %>
          <%= link_to place, class: "btn btn-lg btn-add-to-cart" do %>
          <i class="glyphicon glyphicon-shopping-cart"></i> Меню
          <% end %>
        <% end %>        
      </div>
      <div class="col-md-4 text-right">
        <h4>Количество блюд: <span class="itemPrice"><%= place.items.count %></span></h4>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="row">
	<div class="col-md-8"> 
	  <%= render @places %>
  </div>
  <div class="col-md-4">
	</div>  
</div>

app/views/places/show.html.erb
<div class="row">
	<div class="col-md-8">        
		<%= render @place %>
		<%= render @place.items %>
	</div>
	<div class="col-md-4">
		<%= render 'carts/cart', place: @place if user_signed_in? %>
	</div>
</div>

app/views/users/edit.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :name %>
	<%= f.input :phone %>
	<%= f.input :address %>
	<%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%= @user.name %></h2>
                    <p><strong>Phone: </strong> <%= @user.phone %> </p>
                    <p><strong>Address: </strong> <%= @user.address %> </p>
                </div>             
                <div class="col-xs-12 col-sm-4 text-center">
                    <%= link_to 'Update profile', edit_user_path(@user), class: "btn btn-info btn-block"%>
                    <%= link_to 'Orders', orders_path, class: "btn btn-info btn-block"%>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong> <%= @user.orders.count %> </strong></h2>                 
                    <p><small>Orders</small></p>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>2300</strong></h2>                    
                    <p><small>Spend money</small></p>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>21</strong></h2>                    
                    <p><small>Dish try</small></p>
                </div>
            </div>
    	 </div>                 
		</div>
	</div>
</div>